version: "3.4"

services:
  example_app:
    container_name: example_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    depends_on:
      - redis
    restart: always
    command: ["npm", "start"]
